### ISSUE TITLE
F77_CALL(dgemm) Segmentation fault

### ISSUE THREAD

**Issue by ZahraBoroujeni** [zouhairm/zmpc#1]
Dear all,

I try to run the masses_example using R2016a, ubuntu 14.04. 
I can compile the codes using 
`>> mex -compatibleArrayDims fmpc_step.c -g -lmwblas -lmwlapack -v GCC='/usr/bin/gcc-4.7'`

but the matlab crashed! therefore I run the code using gdb debugger. 
So I run the code like that:

```
matlab -Dgdb
(gdb) run -nojvm
>> dbmex on
>> masses_example 
(gdb) break mexFunction
(gdb) break fmpc_step.c:50
(gdb) break fmpc_step.c:141
(gdb) continue
```

and I got the Segmentation fault in line 141 of "fmpc_step.c" like below:
line 141: `F77_CALL(dgemm)("t","n",&n,&n,&n,&fone,A,&n,eyen,&n,&fzero,At,&n);`

```
Breakpoint 3, mexFunction (nlhs=3, plhs=0x7fffd6a07538, nrhs=5, prhs=0x7fffd6a07458) at /home/mi/boroujeni/fast_mpc-0.0.1/fmpc_step.c:141
141     F77_CALL(dgemm)("t","n",&n,&n,&n,&fone,A,&n,eyen,&n,&fzero,At,&n);
Continuing.
[New Thread 0x7ffff7fca700 (LWP 7693)]
[New Thread 0x7fffc0124740 (LWP 7694)]
[New Thread 0x7fffc00a3780 (LWP 7695)]
[New Thread 0x7fffb1fd17c0 (LWP 7696)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb1fd17c0 (LWP 7696)]
0x00007fffb55f1150 in mkl_blas_avx2_dgemm_dcopy_right12_ea () from /usr/local/MATLAB/R2016a/bin/glnxa64/mkl.so

```

I would appreciate any help or suggestion.

Best,
Zahra

**Comment by zouhairm** [comment]
Sorry I just saw this after almost two years! I hope you had luck fixing it!
